[KAN-12] 회원정보 등록
ureca9/FE_MungGu pull request #14
Opened 2024-11-29 04:07 UTC by ckdwns1221

## 작업

- [ ] 페이지 퍼블리싱
- [ ] 서버에 회원 정보 전송
- [ ] Input 스토리북 구현 후 적용

## 이슈 
없음

## 참고
없음

2024-12-03 11:54 UTC, ckdwns1221 commented on src/api/auth/auth.js
> +      localStorage.clear();
수정완료

2024-12-03 12:02 UTC, ckdwns1221 commented on src/pages/UserPage/UserRegister.jsx
> +  }, []);
기존 코드 유지

2024-12-03 12:07 UTC, ckdwns1221 commented on src/api/userRegister.js
> +      },
수정완료

2024-12-03 12:07 UTC, ckdwns1221 commented on src/api/axios.js
> +    }
수정완료

2024-12-03 12:08 UTC, ckdwns1221 commented on src/api/userRegister.js
> +    }
수정완료

2024-12-03 12:09 UTC, ckdwns1221 commented on src/router/router.jsx
> +  },
수정완료

2024-12-03 12:11 UTC, ckdwns1221 commented on src/pages/UserPage/UserRegister.jsx
> +  };
수정완료

2024-12-03 12:11 UTC, ckdwns1221 commented on src/pages/UserPage/UserRegister.jsx
> +    </div>
기존 코드 유지

2024-12-04 01:03 UTC, heeeione requested changes

2024-12-05 05:20 UTC, heeeione commented on src/api/auth/auth.js
> +        [LOCAL_STORAGE_KEYS.PROFILE_IMAGE]: profileImageUrl,
zustand에 persist 미들웨어를 사용하는 건 어떤가요?

2024-12-06 07:19 UTC, merged